### PR TITLE
Added options bindOnly & wontBind for more control

### PR DESCRIPTION
**Pull request by ffxsam**
I added this package to use it in my own project, but I wanted the ability to not bind certain methods provided by mixins. I decided to make a change so that people have more fine-grained control over auto-binding.

### CODE REVIEW

**Comment by ffxsam** [comment]
PS: any reason you're not using more ES6 in this code? For example, you used `arguments` and `Array.prototype.slice` when you could've used rest/spread arguments:

```
export default function autoBind (context, ...args) {
```

I kept it as close to ES5 as possible just to conform to the project, otherwise I would've done this:

```
wontBind = [...wontBind, ...options.wontBind];
```

**Comment by cassiozen** [comment]
Thanks for the pull request. Being a library, I think it makes sense to make as little assumptions of the projects as possible (including whether the project uses or not ES6).

**Comment by ffxsam** [comment]
You're welcome!

If you're using babel to transpile your code into the lib folder, it's self-contained and people using this package don't necessarily have to use ES6.

**Comment by cassiozen** [comment]
You're absolutely right. What was I thinking? Hehehe.

**Comment by ffxsam** [comment]
I'm happy to keep contributing and do some code cleanup, as long as you don't mind. Thanks for creating this!

**Comment by cassiozen** [comment]
Sure, please do! 

If you want to collaborate, we could start discussing future improvements as well. Out of the top of my head I can think of:

• Better Test coverage
• Bind & memoization for functional components.

What are your thoughts?

**Comment by ffxsam** [comment]
Ha.. well, I'm a total newbie at tests, so I don't know if I can help there. :) I'm not 100% sure what you mean by bind & memoization of functional components. Do you mean stateless functions?

```
const MyComponent = (props) => {
   return <div>Howdy</div>
};
```

**Comment by ffxsam** [comment]
BTW, when will this PR be published to the npm registry?

**Comment by ffxsam** [comment]
@cassiozen Any plans to publish this PR?

**Pull request merged**
